import Link from 'next/link'
import { ArrowRight, Check, CloudRain, HeartPulse, Leaf, Landmark, Users, Waves } from 'lucide-react'
import { Header, Footer, Hero, SectionHeading, PracticeAreaCard, MethodologyStep, InsightCard, CTASection, practiceAreas, methodology, insights } from '@/components/site'

const systemNodes = [
  { label: 'Water', icon: Waves }, { label: 'Climate', icon: CloudRain }, { label: 'Health', icon: HeartPulse }, { label: 'Ecosystems', icon: Leaf }, { label: 'Livelihoods', icon: Users }, { label: 'Governance', icon: Landmark },
]

export default function Page() {
  return <><Header /><main id="main-content"><Hero eyebrow="Sustainable River Basins · Climate · Health" title="Building Resilient River Basins. Improving Lives." description="SURBACH helps governments, communities and development partners turn evidence into practical solutions for water security, climate resilience, environmental sustainability and public health."><div className="mt-8 flex flex-wrap gap-3"><Link href="/what-we-do" className="button-primary">Explore Our Work <ArrowRight size={16} /></Link><Link href="/contact" className="button-secondary-dark">Partner With SURBACH</Link></div></Hero>

  <section className="container-site py-20 md:py-28"><div className="grid gap-14 lg:grid-cols-[.9fr_1.1fr] lg:items-center"><SectionHeading eyebrow="The SURBACH perspective" title="The River Basin is where development connects." description="Water, climate, food systems, ecosystems, health, livelihoods and economic development are not separate challenges. They meet in the Basin — the practical scale where evidence can become coordinated action." /><div className="relative grid grid-cols-2 gap-3 sm:grid-cols-3">{systemNodes.map(({ label, icon: Icon }) => <div key={label} className="flex items-center gap-3 rounded-xl border border-slate-200 bg-surbach-light p-4"><Icon size={18} className="text-surbach-water" strokeWidth={1.7} /><span className="font-open-sans text-sm font-semibold text-surbach-navy">{label}</span></div>)}<div className="col-span-2 flex items-center justify-center rounded-xl border border-surbach-water/30 bg-surbach-navy p-6 sm:col-span-3"><div className="text-center"><Waves className="mx-auto text-surbach-water" size={30} /><div className="mt-2 font-montserrat text-base font-semibold text-white">River Basin</div><div className="mt-1 font-open-sans text-xs text-white/60">The connected system</div></div></div></div></div></section>

  <section className="bg-surbach-light py-20 md:py-28"><div className="container-site"><SectionHeading eyebrow="What we do" title="Integrated expertise for complex Basin challenges" description="We bring together technical disciplines, institutional insight and community knowledge to help partners move from complexity to practical next steps." /><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{practiceAreas.map((area) => <PracticeAreaCard key={area.href} area={area} />)}</div></div></section>

  <section className="container-site py-20 md:py-28"><SectionHeading eyebrow="Our approach" title="From Evidence to Impact" description="A structured methodology for moving from understanding Basin conditions to delivery, capacity and impact." /><div className="mt-12 flex flex-col md:flex-row">{methodology.map((step, index) => <MethodologyStep key={step.number} step={step} last={index === methodology.length - 1} />)}</div><Link href="/our-approach" className="mt-4 inline-flex items-center gap-2 font-open-sans text-sm font-semibold text-surbach-blue">Explore our approach <ArrowRight size={16} /></Link></section>

  <section className="bg-surbach-navy py-20 md:py-24"><div className="container-site"><SectionHeading eyebrow="Development impact" title="Healthy Basins underpin resilient economies and communities." description="Our work is oriented toward the foundations that make inclusive, sustainable development possible." light /><div className="mt-12 grid gap-px overflow-hidden rounded-xl border border-white/10 bg-white/10 sm:grid-cols-2 lg:grid-cols-3">{['Water Security','Climate Resilience','Ecosystem Health','Public Health','Sustainable Livelihoods','Stronger Institutions'].map((item, i) => <div key={item} className="flex items-center gap-4 bg-surbach-navy p-6"><span className="font-mono text-sm text-surbach-water">0{i+1}</span><span className="font-montserrat text-sm font-semibold text-white">{item}</span></div>)}</div></div></section>

  <section className="border-y border-slate-200 bg-surbach-light py-20 md:py-24"><div className="container-site grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><SectionHeading eyebrow="Institutional collaboration" title="Development at Basin scale requires partnership." description="SURBACH collaborates across the institutions, disciplines and communities that shape Basin outcomes — from government and River Basin Development Authorities to research institutions, climate funds and private-sector partners." /><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{['Government','River Basin Authorities','Multilateral Organisations','Development Finance','Research Institutions','Communities'].map((p) => <div key={p} className="rounded-lg bg-white p-4 font-montserrat text-sm font-semibold leading-5 text-surbach-navy shadow-sm">{p}</div>)}</div></div><div className="container-site mt-8"><Link href="/partnerships" className="button-primary">Explore Partnership Opportunities <ArrowRight size={16} /></Link></div></section>

  <section className="container-site py-20 md:py-28"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><SectionHeading eyebrow="Research & insights" title="Evidence for better decisions" description="A knowledge space for research, policy thinking and practical Basin insight." /><Link href="/insights" className="inline-flex items-center gap-2 whitespace-nowrap font-open-sans text-sm font-semibold text-surbach-blue">View all insights <ArrowRight size={16} /></Link></div><div className="mt-12 grid gap-5 lg:grid-cols-2">{insights.map((insight) => <InsightCard key={insight.slug} insight={insight} />)}</div></section>

  <CTASection dark /></main><Footer /></>
}
