import Image from 'next/image'
import Link from 'next/link'
import { ArrowRight, ChevronDown, Droplets, Leaf, Menu, X, Waves, ShieldCheck, HeartPulse, Users, Landmark, FlaskConical, Handshake, Search, MapPin, CalendarDays, Linkedin, Mail, Phone, Building2, Sprout, BookOpen, LineChart, Target, CircleDot } from 'lucide-react'

export const practiceAreas = [
  { title: 'Water Security & Integrated River Basin Management', short: 'Planning and protecting water resources across the systems where communities, ecosystems and economies connect.', href: '/what-we-do/water-security', icon: Droplets, accent: 'water' },
  { title: 'Climate Resilience & Environmental Conservation', short: 'Helping institutions assess climate risk, restore ecosystems and prepare projects for climate finance.', href: '/what-we-do/climate-resilience', icon: Leaf, accent: 'green' },
  { title: 'Health Systems & Community Wellbeing', short: 'Connecting environmental conditions, WASH, public health systems and community wellbeing.', href: '/what-we-do/health', icon: HeartPulse, accent: 'water' },
  { title: 'Capacity Building, Livelihoods & Community Resilience', short: 'Strengthening people, institutions and climate-smart livelihoods for durable local resilience.', href: '/what-we-do/capacity-livelihoods', icon: Users, accent: 'green' },
  { title: 'Governance, Research & Strategic Partnerships', short: 'Turning evidence into policy, coordination, investment readiness and practical delivery.', href: '/what-we-do/governance-research', icon: Landmark, accent: 'water' },
]

export const methodology = [
  { number: '01', title: 'Detect', text: 'Understand Basin conditions, risks and opportunities.', icon: Search },
  { number: '02', title: 'Analyse', text: 'Transform multidisciplinary data into actionable insight.', icon: FlaskConical },
  { number: '03', title: 'Design', text: 'Develop strategies, programmes and implementable solutions.', icon: Target },
  { number: '04', title: 'Mobilise', text: 'Build partnerships and strengthen readiness for investment and finance.', icon: Handshake },
  { number: '05', title: 'Deliver', text: 'Support implementation, capacity development and measurable impact.', icon: ShieldCheck },
]


export const insights = [
  { slug: 'water-diplomacy-rc-irbm-unesco-webinar', title: 'SURBACH Executive Director, AJ. Ochigbo FNMGS, Charts Path for Transformative Water Diplomacy at RC-IRBM/UNESCO Webinar', category: 'News', date: '21 May 2026', author: 'SURBACH', image: '/images/surbach-basin-hero.png', summary: 'AJ. Ochigbo FNMGS served as a panelist at a webinar on transformative water diplomacy in West Africa, outlining Nigeria’s priorities for transboundary water negotiations.' },
  { slug: 'nigeria-uk-pact-climate-negotiation-mentorship', title: 'SURBACH Executive Director Participates as Mentee in Nigeria–UK PACT Climate Negotiation Mentorship Programme', category: 'News', date: '13 August 2026', author: 'SURBACH', image: '/images/surbach-basin-hero.png', summary: 'The Executive Director of SURBACH participated virtually as a mentee in Workshops 5 and 6 of the Nigeria–UK PACT Project: “Enhancing Nigeria’s Capacity in Global Climate Negotiations”.' },
  { slug: 'river-basin-philosophy', title: 'Why the River Basin is the right scale for joined-up development', category: 'Basin Insight', date: '16 August 2026', author: 'SURBACH Editorial Team', image: '/images/surbach-basin-hero.png', summary: 'A practical introduction to connecting water, climate, ecosystems, health and livelihoods in one planning frame.' },
  { slug: 'climate-readiness', title: 'From climate risk to project readiness', category: 'Commentary', date: '16 August 2026', author: 'SURBACH Editorial Team', image: '/images/surbach-basin-hero.png', summary: 'What institutions need to move from vulnerability assessment toward fundable, implementable responses.' },
]

export const team = [
  { name: 'Adoyi John Ochigbo', title: 'Executive Director | Integrated Water Resources Management & Sustainable Development Expert', bio: 'Leads SURBACH’s technical direction across water resources, climate resilience and sustainable development.', expertise: ['IWRM', 'Sustainable Development', 'Strategy'], image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/executive%20director-VEOLj1u3H9bpdJ1KN8uRx31m9lLhgy.jpeg' },
  { name: 'Jonah Adole Ochigbo', title: 'Strategy & Operations Lead', bio: 'Supports organisational strategy, operations and coordination across SURBACH’s workstreams.', expertise: ['Strategy', 'Operations', 'Coordination'], image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dp_jonah-C83A1l7k8GOIt1TC9KelicLHBkYIpY.jpg' },
  { name: 'Maria Ada Ochigbo', title: 'Pharmacy & Public Health Specialist', bio: 'Contributes public-health and community wellbeing expertise to integrated development programmes.', expertise: ['Public Health', 'Community Wellbeing', 'Health Systems'], image: 'https://hebbkx1anhila5yf.public.blob.vercel-storage.com/maria%20ochigbo-mjgIzsJYi3xfgy1j4uaEOYBR65LFFF.webp' },
  { name: 'J. O. Adanu', title: 'ICT & Digital Solutions', bio: 'Supports digital systems, information management and technology-enabled delivery.', expertise: ['ICT', 'Digital Solutions', 'Information'] },
  { name: 'Eugenia Oshin', title: 'Geology & Environmental Specialist', bio: 'Contributes earth-science and environmental perspectives to basin and conservation work.', expertise: ['Geology', 'Environment', 'Field Science'] },
  { name: 'Eunice Odey', title: 'Social Wellbeing & Humanitarian Services', bio: 'Brings community-centred and humanitarian perspectives to resilience and inclusion.', expertise: ['Social Wellbeing', 'Humanitarian Services', 'Communities'] },
]

function Logo({ light = false }: { light?: boolean }) {
  return <Link href="/" className={`flex items-center ${light ? 'rounded-lg bg-white px-2 py-1' : ''}`} aria-label="SURBACH home"><Image src="https://hebbkx1anhila5yf.public.blob.vercel-storage.com/SURBACH%20logo-DgsQAFwGIlI0YsGVvzhpsU30M8U70f.jpeg" alt="SURBACH logo" width={156} height={156} className="h-14 w-14 object-contain md:h-16 md:w-16" priority /></Link>
}

function HeaderStatic() {
  const open = false
  const links = [['About','/about'],['What We Do','/what-we-do'],['Our Approach','/our-approach'],['Insights','/insights'],['Partnerships','/partnerships'],['Team','/team'],['Contact','/contact']]
  return <><a href="#main-content" className="sr-only focus:not-sr-only focus:fixed focus:left-4 focus:top-4 focus:z-50 focus:bg-surbach-navy focus:px-4 focus:py-2 focus:text-white">Skip to content</a><header className="sticky top-0 z-40 border-b border-slate-200/80 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-4 md:px-6 lg:px-8"><Logo /><nav className="hidden items-center gap-6 lg:flex">{links.map(([label, href]) => <Link key={href} href={href} className="font-open-sans text-sm font-semibold text-surbach-navy/80 transition-colors hover:text-surbach-water">{label}</Link>)}</nav><div className="hidden lg:block"><Link href="/contact" className="button-primary px-5 py-3">Partner With Us <ArrowRight size={16} /></Link></div><button className="rounded-lg p-2 text-surbach-navy lg:hidden" aria-label={open ? 'Close menu' : 'Open menu'} aria-expanded={open}>{open ? <X /> : <Menu />}</button></div>{open && <div className="border-t border-slate-200 bg-white px-4 py-5 lg:hidden"><nav className="flex flex-col gap-1">{links.map(([label, href]) => <Link key={href} href={href} className="rounded-lg px-3 py-3 font-open-sans font-semibold text-surbach-navy hover:bg-surbach-light">{label}</Link>)}<Link href="/contact" className="button-primary mt-3 justify-center">Partner With Us <ArrowRight size={16} /></Link></nav></div>}</header></>
}

export function Footer() { return <footer className="bg-surbach-navy text-white"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-16 md:grid-cols-2 md:px-6 lg:grid-cols-[1.5fr_1fr_1fr_1fr] lg:px-8"><div><Logo light /><p className="mt-5 max-w-sm font-open-sans text-sm leading-7 text-white/70">Integrated solutions for resilient River Basins, healthy communities and sustainable development.</p><div className="mt-6 flex items-start gap-3 text-sm leading-6 text-white/70"><MapPin size={16} className="mt-1 shrink-0" /><span>No. 1, Ibadan Street, Suite GF007, AICL Area 3 Neighbourhood Shopping Centre, Garki, Abuja, FCT, Nigeria</span></div><a href="mailto:info@surbach.org" className="mt-4 flex items-center gap-3 font-open-sans text-sm text-white/70 transition-colors hover:text-white"><Mail size={16} /> info@surbach.org</a></div><FooterColumn title="Organisation" links={[['About SURBACH','/about'],['Our Team','/team'],['Our Approach','/our-approach'],['Contact','/contact']]} /><FooterColumn title="Our Work" links={[['Practice Areas','/what-we-do'],['Partnerships','/partnerships']]} /><FooterColumn title="Knowledge" links={[['Research & Insights','/insights'],['Water Security','/what-we-do/water-security'],['Climate Resilience','/what-we-do/climate-resilience']]} /></div><div className="border-t border-white/10"><div className="mx-auto flex max-w-7xl flex-col gap-3 px-4 py-6 text-xs text-white/55 md:flex-row md:items-center md:justify-between md:px-6 lg:px-8"><span>Sustainable Development of River Basin, Climate Action and Health Solutions Ltd/Gte</span><span><Link href="/privacy" className="hover:text-white">Privacy Policy</Link> · <Link href="/terms" className="hover:text-white">Terms</Link> · <span>Accessibility</span></span></div></div></footer> }
function FooterColumn({ title, links }: { title: string; links: string[][] }) { return <div><h3 className="font-montserrat text-sm font-semibold text-white">{title}</h3><div className="mt-5 flex flex-col gap-3">{links.map(([label, href]) => <Link key={href} href={href} className="font-open-sans text-sm text-white/65 transition-colors hover:text-white">{label}</Link>)}</div></div> }

export function SectionHeading({ eyebrow, title, description, light = false }: { eyebrow?: string; title: string; description?: string; light?: boolean }) { return <div className="max-w-2xl"><div className={`section-eyebrow ${light ? 'text-surbach-water' : 'text-surbach-water'}`}>{eyebrow || 'SURBACH'}</div><h2 className={`mt-3 font-montserrat text-3xl font-semibold tracking-tight md:text-4xl ${light ? 'text-white' : 'text-surbach-navy'}`}>{title}</h2>{description && <p className={`mt-5 font-open-sans text-base leading-7 ${light ? 'text-white/70' : 'text-slate-600'}`}>{description}</p>}</div> }

export function CTASection({ dark = false }: { dark?: boolean }) { return <section className={dark ? 'bg-surbach-navy' : 'bg-surbach-light'}><div className="mx-auto flex max-w-7xl flex-col gap-8 px-4 py-16 md:flex-row md:items-center md:justify-between md:px-6 lg:px-8"><div className="max-w-2xl"><div className={`section-eyebrow ${dark ? 'text-surbach-water' : 'text-surbach-blue'}`}>Start a conversation</div><h2 className={`mt-3 font-montserrat text-3xl font-semibold ${dark ? 'text-white' : 'text-surbach-navy'}`}>Let&apos;s build more resilient Basins together.</h2><p className={`mt-4 font-open-sans leading-7 ${dark ? 'text-white/70' : 'text-slate-600'}`}>Whether you are developing policy, strengthening Basin institutions, designing a programme or preparing an investment, SURBACH brings multidisciplinary expertise to the table.</p></div><div className="flex flex-wrap gap-3"><Link href="/contact" className="button-primary">Partner With Us <ArrowRight size={16} /></Link><Link href="/contact" className={dark ? 'button-secondary-dark' : 'button-secondary'}>Contact SURBACH</Link></div></div></section> }

export function PracticeAreaCard({ area }: { area: typeof practiceAreas[number] }) { const Icon = area.icon; return <Link href={area.href} className="group flex h-full flex-col rounded-xl border border-slate-200 bg-white p-6 transition-all hover:-translate-y-1 hover:border-surbach-water/40 hover:shadow-lg"><span className={`mb-8 flex h-11 w-11 items-center justify-center rounded-lg ${area.accent === 'green' ? 'bg-surbach-green/10 text-surbach-green' : 'bg-surbach-water/10 text-surbach-water'}`}><Icon size={22} strokeWidth={1.7} /></span><h3 className="font-montserrat text-lg font-semibold leading-7 text-surbach-navy">{area.title}</h3><p className="mt-3 flex-1 font-open-sans text-sm leading-6 text-slate-600">{area.short}</p><span className="mt-6 inline-flex items-center gap-2 font-open-sans text-sm font-semibold text-surbach-blue">Explore practice area <ArrowRight size={15} className="transition-transform group-hover:translate-x-1" /></span></Link> }

export function MethodologyStep({ step, last = false }: { step: typeof methodology[number]; last?: boolean }) { const Icon = step.icon; return <div className="relative flex gap-4 md:block md:flex-1 md:pr-5">{!last && <span className="absolute left-5 top-11 h-[calc(100%+1rem)] w-px bg-surbach-water/30 md:left-0 md:top-5 md:h-px md:w-[calc(100%-1.5rem)]" />}<div className="relative flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-surbach-water text-white"><Icon size={18} /></div><div className="pb-8 md:pt-5"><span className="font-mono text-xs font-semibold tracking-widest text-surbach-water">{step.number}</span><h3 className="mt-2 font-montserrat text-lg font-semibold text-surbach-navy">{step.title}</h3><p className="mt-2 max-w-xs font-open-sans text-sm leading-6 text-slate-600">{step.text}</p></div></div> }

export function InsightCard({ insight }: { insight: typeof insights[number] }) { return <article className="group overflow-hidden rounded-xl border border-slate-200 bg-white"><div className="relative aspect-[16/9]"><Image src={insight.image} alt="River basin landscape" fill className="object-cover transition-transform duration-500 group-hover:scale-105" /></div><div className="p-5"><div className="flex items-center justify-between text-xs font-semibold"><span className="text-surbach-blue">{insight.category}</span><span className="flex items-center gap-1 text-slate-500"><CalendarDays size={13} /> {insight.date}</span></div><h3 className="mt-3 font-montserrat text-lg font-semibold leading-7 text-surbach-navy">{insight.title}</h3><p className="mt-3 font-open-sans text-sm leading-6 text-slate-600">{insight.summary}</p><div className="mt-5 flex items-center justify-between"><span className="font-open-sans text-xs text-slate-500">By {insight.author}</span><Link href={`/insights/${insight.slug}`} className="inline-flex items-center gap-2 font-open-sans text-sm font-semibold text-surbach-blue">Read insight <ArrowRight size={15} /></Link></div></div></article> }

export function TeamMember({ member }: { member: typeof team[number] }) { return <article className="rounded-xl border border-slate-200 bg-white p-6"><div className="relative h-24 w-24 overflow-hidden rounded-full bg-surbach-light text-surbach-blue">{'image' in member && member.image ? <Image src={member.image} alt={`${member.name} profile photo`} fill className="object-cover" sizes="96px" /> : <div className="flex h-full w-full items-center justify-center"><Users size={28} strokeWidth={1.4} /></div>}</div><h3 className="mt-5 font-montserrat text-lg font-semibold text-surbach-navy">{member.name}</h3><p className="mt-2 font-open-sans text-sm font-semibold leading-6 text-surbach-blue">{member.title}</p><p className="mt-4 font-open-sans text-sm leading-6 text-slate-600">{member.bio}</p><div className="mt-5 flex flex-wrap gap-2">{member.expertise.map((tag) => <span key={tag} className="rounded-md bg-surbach-light px-2.5 py-1 font-open-sans text-xs font-semibold text-surbach-navy">{tag}</span>)}</div></article> }

export function Hero({ eyebrow, title, description, image = true, children }: { eyebrow: string; title: string; description: string; image?: boolean; children?: React.ReactNode }) { return <section className="relative overflow-hidden bg-surbach-navy"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 py-16 md:px-6 md:py-24 lg:grid-cols-[1fr_0.9fr] lg:px-8 lg:py-28"><div className="relative z-10"><div className="section-eyebrow text-surbach-water">{eyebrow}</div><h1 className="mt-5 max-w-3xl font-montserrat text-4xl font-semibold leading-tight tracking-tight text-white md:text-5xl">{title}</h1><p className="mt-6 max-w-2xl font-open-sans text-base leading-7 text-white/75 md:text-lg">{description}</p>{children}</div>{image && <div className="relative aspect-[4/3] overflow-hidden rounded-2xl border border-white/15"><Image src="/images/surbach-basin-hero.png" alt="A Nigerian river basin landscape" fill priority className="object-cover" /><div className="absolute inset-0 bg-gradient-to-tr from-surbach-navy/35 to-transparent" /><div className="absolute bottom-4 left-4 flex items-center gap-2 rounded-lg bg-surbach-navy/80 px-3 py-2 font-mono text-[10px] tracking-widest text-white/80"><CircleDot size={12} className="text-surbach-water" /> BASIN SYSTEMS · NIGERIA</div></div>}</div></section> }

export function PartnerCategory({ title, icon: Icon = Building2 }: { title: string; icon?: typeof Building2 }) { return <div className="flex items-center gap-4 rounded-xl border border-slate-200 bg-white p-5"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-surbach-water/10 text-surbach-water"><Icon size={19} /></span><span className="font-montserrat text-sm font-semibold leading-5 text-surbach-navy">{title}</span></div> }

export { Header } from './header'
export { Logo, Mail, Phone }
