import Link from 'next/link'
import { notFound } from 'next/navigation'
import { ArrowRight, CheckCircle2 } from 'lucide-react'
import { Header, Footer, Hero, SectionHeading, CTASection } from '@/components/site'

const details: Record<string, { eyebrow: string; title: string; context: string; response: string; capabilities: string[]; deliverables: string[] }> = {
  'water-security': { eyebrow: 'Practice area 01', title: 'Water Security & Integrated River Basin Management', context: 'Water security depends on understanding the whole system: source waters, catchments, infrastructure, demand, quality, risk and governance.', response: 'SURBACH supports partners to assess Basin conditions and translate those findings into integrated planning, protection and investment decisions.', capabilities: ['Integrated River Basin planning','Integrated Water Resources Management','Water-resource assessment','Water-quality analysis','Sediment monitoring','Source-water protection','Flood and drought risk management','Catchment management','Water infrastructure / project appraisal','Transboundary water governance'], deliverables: ['Basin diagnostics and assessments','Water-resource plans and decision frameworks','Risk and vulnerability analyses','Project appraisal and readiness support'] },
  'climate-resilience': { eyebrow: 'Practice area 02', title: 'Climate Resilience & Environmental Conservation', context: 'Climate risk is experienced through water, land, ecosystems, livelihoods and public health. Responses need to be grounded in place and ready for implementation.', response: 'We help institutions assess vulnerability, identify adaptation options, protect ecosystems and develop climate projects that can attract the right partnerships and finance.', capabilities: ['Climate vulnerability assessment','Climate adaptation planning','Mitigation','Nature-based solutions','Ecosystem restoration','Wetland conservation','Watershed conservation','Renewable-energy advocacy','Climate project development','Climate-finance readiness'], deliverables: ['Climate risk and vulnerability assessments','Adaptation and conservation strategies','Nature-based solution concepts','Climate-finance concept notes'] },
  'health': { eyebrow: 'Practice area 03', title: 'Health Systems & Community Wellbeing', context: 'Environmental conditions, water access, sanitation, livelihoods and health systems shape one another. Basin resilience must include human wellbeing.', response: 'SURBACH connects environmental health, community health and health-systems perspectives to support prevention, preparedness and stronger local delivery.', capabilities: ['Environmental health','Community health','Disease prevention','Health systems strengthening','Health supply chains','WASH-related health programmes','Health education','Public-health research','Vulnerable-population programmes'], deliverables: ['Community health assessments','WASH and health programme design','Health education and prevention materials','Public-health research and learning'] },
  'capacity-livelihoods': { eyebrow: 'Practice area 04', title: 'Capacity Building, Livelihoods & Community Resilience', context: 'Resilience is built through people and institutions with the skills, relationships and resources to act before, during and after disruption.', response: 'We design practical capacity, livelihood and community-resilience support that responds to local realities and creates room for participation.', capabilities: ['Youth development','Women empowerment','Water entrepreneurship','Agripreneurship','Climate-smart livelihoods','Mentorship','Workshops','Technical training','Institutional capacity development'], deliverables: ['Training and mentorship programmes','Climate-smart livelihood models','Institutional capacity plans','Community engagement frameworks'] },
  'governance-research': { eyebrow: 'Practice area 05', title: 'Governance, Research & Strategic Partnerships', context: 'Evidence only changes outcomes when it is understood, trusted and connected to decisions, institutions and resources.', response: 'SURBACH helps partners build the research, policy, coordination and partnership architecture needed for Basin-level action.', capabilities: ['Applied research','Policy analysis','Institutional strengthening','Stakeholder engagement','Conflict-resolution support','Legislative support','Partnership development','Multi-stakeholder coordination','Knowledge products','Programme design'], deliverables: ['Research and policy products','Stakeholder and governance assessments','Programme and partnership strategies','Knowledge and learning systems'] },
}

export function generateStaticParams() { return Object.keys(details).map((slug) => ({ slug })) }
export default async function PracticeDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const detail = details[slug]; if (!detail) notFound(); return <><Header /><main id="main-content"><Hero eyebrow={detail.eyebrow} title={detail.title} description={detail.context}><div className="mt-8"><Link href="/contact" className="button-primary">Discuss a need <ArrowRight size={16} /></Link></div></Hero><section className="container-site grid gap-12 py-20 md:py-28 lg:grid-cols-[.8fr_1.2fr]"><SectionHeading eyebrow="Our response" title="Technical advice that can move toward delivery." description={detail.response} /><div><h2 className="font-montserrat text-2xl font-semibold text-surbach-navy">Capabilities</h2><div className="mt-6 grid gap-3 sm:grid-cols-2">{detail.capabilities.map((item) => <div key={item} className="flex gap-3 border-b border-slate-200 pb-3 font-open-sans text-sm leading-6 text-slate-700"><CheckCircle2 className="mt-1 shrink-0 text-surbach-green" size={16} />{item}</div>)}</div></div></section><section className="bg-surbach-light py-20"><div className="container-site grid gap-10 md:grid-cols-2"><div><SectionHeading eyebrow="Potential deliverables" title="Outputs designed for the next decision." /></div><div className="grid gap-3">{detail.deliverables.map((item) => <div key={item} className="rounded-lg border border-slate-200 bg-white p-5 font-open-sans text-sm font-semibold text-surbach-navy">{item}</div>)}</div></div></section><CTASection dark /></main><Footer /></> }
